### ISSUE TITLE
[ REFACTOR ] - Update ActivityLog, UserJobApplication table

### ISSUE THREAD

**Issue by nar0ng** [nar0ng/9th-Growing-Pain-BE#2]
# 🛠️ Description for refactoring features
리팩토링 작업할 사항에 대해 작성해주세요.

> 활동기록
 - 기여도의 데이터타입을 int형으로 변경합니다.
 - 활동기록의 날짜 포맷 -> 프론트: string 요청
 - 활동내용에 이미지, 파일 파일 추가합니다.
 

> 지원현황
 - d-day 추가 : 공고기간과 현재날짜를 계산해서 전달합니다. => 프론트에서 작업하신다고 하십니다.
 - 지원현황 타입에 '면접 피드백 추가', '기업 분석' 타입 추가합니다.

## 📝 Todo-lists
- [x] 활동기록
- [x] 기여도의 데이터타입을 int형으로 변경
- [x] 활동내용에 이미지, 파일 파일 추가
- [x] 지원현황
- [x] 지원현황 타입에 '면접 피드백 추가', '기업 분석' 타입 추가
- [x] 지원현황의 날짜기록 string으로 변경
